### ISSUE TITLE
Should show an error message when unable to fetch COVID 19 data from api.

### ISSUE THREAD

**Issue by kartik3805** [kartik3805/AskWeather#1]
When unable to fetch data from Api, it shows a blank space
Add functionality to show an error message in this situation so that it doesn't look broken

Preview:

<img width="632" alt="Blank space when unable to fetch data" src="https://user-images.githubusercontent.com/94182623/193894456-843f3a91-7fc6-477e-8051-2847a27a37f9.PNG">

**Comment by joanjeremiah** [comment]
I would like to solve this issue. Kindly assign this to me.

**Comment by joanjeremiah** [comment]
I made a pull request. Kindly look into it  and let me know if I need to make any changes
