### ISSUE TITLE
[BUG] wbesite is Not responsive

### ISSUE THREAD

**Issue by rupali-codes** [kartik3805/AskWeather#11]
Not having a responsive website may create trouble for Mobile and other screen users, and also responsible it's for a Bad User Experience with the site. 

Here's what I got: 

![image](https://user-images.githubusercontent.com/78981177/194743177-952f5326-1c0e-44a6-9246-e45d862e949e.png)

![image](https://user-images.githubusercontent.com/78981177/194743229-3f5db08a-a033-4b9d-9e68-30df50ddc2bf.png)

![image](https://user-images.githubusercontent.com/78981177/194743257-21cc8e5d-ba13-4b12-9618-2a3010666d57.png)

**Comment by rupali-codes** [comment]
I'm happy to work on it, can this issue be assigned to me?

**Comment by kartik3805** [comment]
> I'm happy to work on it, can this issue be assigned to me?

Sometimes it is unresponsive only in inspect mode (reloading page will resolve the issue), not in real mobile devices

**Comment by rupali-codes** [comment]
just realized, thanks :)
